# Generated by Django 5.2.9 on 2025-12-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_expense_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
